### ISSUE TITLE
S130 SoftDevice Linking

### ISSUE THREAD

**Issue by jhester** [lab11/nrf5x-base#10]
The current linker script for the S130 device did not work for me with a custom nrf51822_XXAC board. The mem locations below did work, gleaned from [the S130 spec](http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.pdf.sds/S130_SDS_v1.0.pdf). Has anyone else had this problem?

```
/* S130  Linker script to configure memory regions. */
MEMORY
{
  FLASH (rx) : ORIGIN = 0x0 + 108K + 4K, LENGTH = 256K - 112K /* 112 kB is taken by S130, 144 kB for app. */
  RAM (rwx) : ORIGIN = 0x20000000 + 10K, LENGTH = 32K - 10K /* 10 kB is taken by S130, 22 kB for app. */
}
INCLUDE "gcc_nrf51_common.ld"
```

**Comment by bradjc** [comment]
I don't think we've used the S130 much. I updated the ld file with your working version.
