### ISSUE TITLE
License for simple_ble simple_adv and other nrf5x-base code

### ISSUE THREAD

**Issue by karlbloedorn** [lab11/nrf5x-base#11]
Which license is the nrf5x-base project under? 
I would like to use in commercial hardware and contribute some small features back but cannot use beyond prototyping until a license is known.

**Comment by brghena** [comment]
Karl

I updated the code today to place all of our code under the MIT License. See the LICENSE file in the root directory. Note that this does not apply to the make, softdevice, and sdk directories, which are separately licensed as noted. Make by hlnd who we originally forked this code from. Softdevice and SDK by Nordic Semi, and are only located in this repo as a convenience.

If you've got any questions (licenses or usage), let us know. We're happy to have someone using the project and are glad to accept pull requests.

Thanks
Branden
(MTU CpE Class of 2013. Go Tech!)
