### ISSUE TITLE
Question; Is the current makefile manage C++ (.cpp) file ?

### ISSUE THREAD

**Issue by fletort** [lab11/nrf5x-base#12]

**Comment by brghena** [comment]
I think you question is whether the current makefile support C++?

The answer is no, we only support C files right now.

**Comment by fletort** [comment]
ok thanks, it hard to add or not ? I will try to see that.

**Comment by brghena** [comment]
I'm not exactly sure how hard it would be, but if you look into it and find a solution, we are happy to take pull requests.
