### ISSUE TITLE
no support for nrf51 in SDK14 

### ISSUE THREAD

**Issue by akohlsmith** [lab11/nrf5x-base#34]
The Makefile specifically omits nrf51 support when SDK 14 is selected. If I omit this specific check my test code seems to work fine with SDK 14.

**Comment by nealjack** [comment]
NRF51 is not supported by SDK 14. The last SDK to support the NRF51 is SDK 12

**Comment by akohlsmith** [comment]
wow, that seems incredibly short sighted of Nordic given the popularity and wide adoption of their nrf51 devices. Thanks for pointing this out!
