### ISSUE TITLE
Enable individual GCC optimization flags

### ISSUE THREAD

**Issue by abiri** [lab11/nrf5x-base#36]
Currently, most `make` files already include an initial `CFLAGS += -Os` to optimize for binary code size. To make sure that this is always the case, the same step is repeated in `/make/Makefile`, line 237.

The issue with the current implementation is that developers in fact do *not* have the freedom to choose their optimization level. As GCC [only takes the last optimization flag into consideration](https://stackoverflow.com/questions/5557261/gcc-multiple-optimization-flags),  anything declared in the local `make` file will be ignored. Apart from being a bug, this behaviour is especially a nuisance when trying to debug, as any locally defined `-Og` flag is ignored. Of course, this can be solved by manually deleting the optimization flag overwrite in `/make/Makefile`.

As an easy solution, I propose changing line 237 from `CFLAGS += -Os` to `CFLAGS ?= -Os` , as this will only be used if CFLAGS has not been defined (possibly with a different optimization flag) before. Of course, this might result in no optimization flag if the developer declares CFLAGS and forgets to add an optimization level himself; however, in my view such a change is in the responsibility of the developer and not this repo.

**Comment by brghena** [comment]
Good find Andreas! Make a PR and we will be happy to pull it.
